version: "3"
services:
  adserver-providers:
    build:
      context: .
      dockerfile: ./adserver-providers/Dockerfile
    ports:
      - "2323:2323"

  adserver-analytics:
    build:
      context: .
      dockerfile: ./adserver-analytics/Dockerfile
    ports:
      - "3030:3030"